### PR TITLE
Update school page. https://codio.myjetbrains.com/youtrack/issueMobile/codio-6762

### PR DESCRIPTION
**Pull request by denpira**
Update school landing page. Issue https://codio.myjetbrains.com/youtrack/issueMobile/codio-6762

### CODE REVIEW

**Comment by denpira** [comment]
Update school landing page. Issue https://codio.myjetbrains.com/youtrack/issueMobile/codio-6762

**Comment by mloginov** [comment]
https://codio.myjetbrains.com/youtrack/issue/codio-6762

**Comment by vvlevykin** [comment]
The photo has to be in JPEG (95% quality), not PNG.

**Comment by vvlevykin** [comment]
Using `pngquant --speed 1` and after that `zopflipng --lossy_transparent --iterations=15 --filters=01234mepb` it's possible to reduce size of png logos from 1.2MB to 388KB.

**Comment by denpira** [comment]
Image processed

**Comment by mloginov** [comment]
:+1:

**Comment by vvlevykin** [comment]
> The photo has to be in JPEG (95% quality), not PNG.

**Comment by denpira** [comment]
Done

**Comment by vvlevykin** [comment]
:+1:

**Pull request merged**
