### PR TITLE
Reduce images size

### PR DESCRIPTION
**Pull request by LeoIannacone**
Issue ??

### CODE REVIEW

**Comment by destitutus** [comment]
image

**Comment by LeoIannacone** [comment]
Image changes too much when quality is < 100

**Comment by destitutus** [comment]
> Image changes too much when quality is < 100

do you really can see a difference between quality 100 and 90?

**Comment by LeoIannacone** [comment]
>> Image changes too much when quality is < 100

> do you really can see a difference between quality 100 and 90?

Yes I do

**Comment by Dignifiedquire** [comment]
:+1:

**Comment by destitutus** [comment]
>> Image changes too much when quality is < 100
>> do you really can see a difference between quality 100 and 90?
>> Yes I do

for me is better load 41k instead of 411k and see and small difference in images

**Comment by vvlevykin** [comment]
The biggest jpegs still can be reduced, I think. They are almost 1MB

**Comment by LeoIannacone** [comment]
I did my tries to have smaller images. If you don't want loose quality, you have to go with these ones.

**Comment by vvlevykin** [comment]
:shipit: :ship: :100: :rocket:

**Comment by Dignifiedquire** [comment]
ship it

**Pull request merged**
